version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Docker/registro-horas-api.Dockerfile
    volumes:
      - ./registro-horas-api:/home/node/api
    networks:
      - registro-horas-backend
    ports:
      - '3001:3001'

networks:
  registro-horas-backend:
      driver: bridge